version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
      - "9005:9005"
    tty: true
    volumes:
      - .:/app:delegated
      - node_modules:/app/node_modules:delegated
    restart: always
volumes:
  node_modules: {}
